Repository knu-datastreams/BigPicture-APP, pull requests merged in 2025-05, with the labels that each got.

#19 API 연동 확인 및 테스트
  .idea/AndroidProjectSystem.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/businessreportgenerator/MainActivity.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/RemoteApiService.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/RetrofitClient.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/Schedule.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystViewmodel.kt
  app/src/main/res/xml/networksecurityconfig.xml
Labels: ✅ Test Code

#24 서버 연결 테스트 코드 관련 리팩토링 및 뷰모델 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/businessreportgenerator/MainActivity.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/ApiViewModel.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/RemoteApiService.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/api/ReportApiService.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/api/ScheduleApiService.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/model/Schedule.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/network/RetrofitClient.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/repository/ApiRepository.kt
  app/src/main/java/com/example/businessreportgenerator/data/repository/ReportRepositoryImpl.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/navigation/AppEntryPoint.kt
Labels: ♻️ Refactoring

#29 refactor : @SuppressLint 오류 해결
  app/src/main/java/com/example/businessreportgenerator/notification/Notification.kt
Labels: 😡 Bug Fix

#33 Mseunghwan
  app/src/main/java/com/example/businessreportgenerator/data/domain/AnalystReport.kt
  app/src/main/java/com/example/businessreportgenerator/data/domain/Asset.kt
  app/src/main/java/com/example/businessreportgenerator/data/domain/Report.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/converter/ReportTypeConverter.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/dao/AssetDao.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/dao/ReportDao.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/entity/AssetEntity.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/entity/ReportEntity.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/repository/AssetRepository.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/repository/ReportRepository.kt
  app/src/main/java/com/example/businessreportgenerator/data/mapper/ReportMapper.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/model/ReportDTO.kt
  app/src/main/java/com/example/businessreportgenerator/di/ServiceLocator.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystSample.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystScreen.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystViewModelFactory.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystViewmodel.kt
Labels: ✨ Feature, ♻️ Refactoring

#35 앱 시작 시 사용하는 로직 변경
  app/src/main/java/com/example/businessreportgenerator/MainActivity.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/AppDatabase.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/StockViewModel.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/dao/StockDao.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/entity/StockEntity.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/repository/RepositoryInterfaces.kt
  app/src/main/java/com/example/businessreportgenerator/data/local/repository/StockRepository.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/api/ReportApiService.kt
  app/src/main/java/com/example/businessreportgenerator/data/remote/model/StockDTO.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/analyst/AnalystViewmodel.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/features/portfolio/PortfolioScreen.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/navigation/AppEntryPoint.kt
  app/src/main/java/com/example/businessreportgenerator/presentation/onboarding/OnboardingScreen.kt
Labels: ✨ Feature

#37 feat : 게시판 기능 추가(게시판 API 연결)
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/bigPicture/businessreportgenerator/data/domain/Board.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/local/repository/BoardRepository.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/ApiResponse.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/api/BoardApiService.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/api/CommentApiService.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/model/BoardDTO.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/model/CommentDTO.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/network/RetrofitClient.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/di/AppModule.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/di/BoardModule.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/features/board/BoardPostCard.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/features/board/BoardScreen.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/features/board/BoardViewModel.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/navigation/MainScreen.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/navigation/NavigationItem.kt
Labels: ✨ Feature

#40 UI 통합 및 로딩창, 환율 API 연결 완료
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bigPicture/businessreportgenerator/MainActivity.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/local/AppDatabase.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/local/StockViewModel.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/ApiViewModel.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/api/CommentApiService.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/api/InterestApiService.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/dto/InterestDTO.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/data/remote/network/RetrofitClient.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/features/news/NewsScreen.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/features/news/NewsViewModel.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/navigation/AppEntryPoint.kt
  app/src/main/java/com/bigPicture/businessreportgenerator/presentation/navigation/LoadingScreen.kt
Labels: ✨ Feature
